set(SDKCONFIG_DEFAULTS
    boards/sdkconfig.240mhz
    boards/sdkconfig.base16m
    boards/sdkconfig.ble
    boards/sdkconfig.spirambs
)

set(MICROPY_FROZEN_MANIFEST ${MICROPY_BOARD_DIR}/manifest.py)

set(CONFIG_MICROPYTHON_LVGL_ENABLE      ON)
set(CONFIG_MICROPYTHON_ESPIDF_ENABLE    ON)
set(CONFIG_MICROPYTHON_LODEPNG_ENABLE   ON)

set(CONFIG_MICROPYTHON_LVGL_COLOR_DEPTH 16)
set(CONFIG_MICROPYTHON_LVGL_COLOR_SWAP  1)
set(CONFIG_MICROPYTHON_LVGL_HOR_RES     240)
set(CONFIG_MICROPYTHON_LVGL_VER_RES     240)


